# Install taps
tap 'caskroom/cask'

# Install system dependencies
brew 'brew-cask'
brew 'node'
brew 'wget'
brew 'wp-cli'

# Install applications
cask 'alfred'
cask 'bettertouchtool'
cask 'caffeine'
cask 'dropbox'
cask 'filezilla'
cask 'firefox'
cask 'flux'
cask 'google-chrome'
cask 'iterm2'
cask 'phpstorm'
cask 'sourcetree'
cask 'spotify'
cask 'steam'
cask 'sublime-text'
cask 'transmission'
cask 'vlc'
